# Generated by Django 6.0.3 on 2026-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0002_alter_appointment_status_alter_therapy_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=10),
        ),
    ]
