# Generated by Django 6.0.3 on 2026-03-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
