# Generated by Django 6.0.3 on 2026-03-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('before_therapy', models.TextField(blank=True, null=True)),
                ('after_therapy', models.TextField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precautions', to='therapies.therapy')),
            ],
        ),
    ]
