# Generated by Django 6.0.3 on 2026-03-31 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_therapy_appointment'),
        ('therapies', '0008_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='instructions',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(default='Not specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapy',
            name='description',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapy',
            name='precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_appointments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_precautions', to='therapies.therapy'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='therapies.appointment'),
        ),
    ]
