# Generated by Django 6.0.3 on 2026-04-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0010_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precaution',
            old_name='after_therapy',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='precaution',
            name='before_therapy',
        ),
        migrations.RemoveField(
            model_name='precaution',
            name='general_notes',
        ),
        migrations.RemoveField(
            model_name='precaution',
            name='therapy',
        ),
        migrations.RemoveField(
            model_name='precaution',
            name='title',
        ),
        migrations.AddField(
            model_name='precaution',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapies.appointment'),
        ),
        migrations.AddField(
            model_name='precaution',
            name='type',
            field=models.CharField(blank=True, choices=[('before', 'Before Therapy'), ('after', 'After Therapy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('before', 'Before Therapy'), ('after', 'After Therapy')], max_length=10)),
                ('morning', models.TextField(blank=True, null=True)),
                ('afternoon', models.TextField(blank=True, null=True)),
                ('evening', models.TextField(blank=True, null=True)),
                ('night', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapies.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('before', 'Before Therapy'), ('after', 'After Therapy')], max_length=10)),
                ('morning', models.TextField(blank=True, null=True)),
                ('afternoon', models.TextField(blank=True, null=True)),
                ('evening', models.TextField(blank=True, null=True)),
                ('night', models.TextField(blank=True, null=True)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapies.therapy')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('before', 'Before Therapy'), ('after', 'After Therapy')], max_length=10)),
                ('text', models.TextField()),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapies.therapy')),
            ],
        ),
    ]
