# Generated by Django 6.0.3 on 2026-04-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0011_rename_after_therapy_precaution_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precaution',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precautions', to='therapies.appointment'),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='type',
            field=models.CharField(choices=[('before', 'Before Therapy'), ('after', 'After Therapy')], max_length=10),
        ),
    ]
