# Generated by Django 6.0.3 on 2026-04-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0012_alter_precaution_appointment_alter_precaution_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapydietplan',
            name='afternoon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapydietplan',
            name='evening',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapydietplan',
            name='morning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapydietplan',
            name='night',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapydietplan',
            name='therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_diets', to='therapies.therapy'),
        ),
        migrations.AlterField(
            model_name='therapyprecaution',
            name='therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_precautions', to='therapies.therapy'),
        ),
    ]
