# Generated by Django 6.0.3 on 2026-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0013_alter_therapydietplan_afternoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapydietplan',
            name='afternoon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapydietplan',
            name='evening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapydietplan',
            name='morning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapydietplan',
            name='night',
            field=models.TextField(blank=True, null=True),
        ),
    ]
