# Generated by Django 6.0.3 on 2026-04-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0014_alter_therapydietplan_afternoon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
