# Generated by Django 6.0.3 on 2026-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_user'),
        ('therapies', '0009_rename_notes_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='therapies',
            field=models.ManyToManyField(blank=True, to='therapies.therapy'),
        ),
    ]
