# Generated by Django 6.0.3 on 2026-04-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='therapies',
        ),
    ]
