# Generated by Django 6.0.3 on 2026-04-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patient_phone_dietplan_precaution_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='precaution',
            name='patient',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='therapy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='patients.therapy'),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='therapy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precautions', to='patients.therapy'),
        ),
    ]
